### ISSUE TITLE
cntrl-click to jump to method definition

### ISSUE THREAD

**Issue by shiffman** [processing/processing-experimental#11]
I'm finding this a bit awkward on Mac OSX since "cntrl-click" is also used for right-click.  So if I try to right-click, I am immediately taken away.  Eclipse uses F3 (not that I love that).  What other choices do we have?

**Comment by Manindra29** [comment]
Cmd + Click should work too? I remember adding that..

**Comment by shiffman** [comment]
ah, yes, it does!  I think we even had this conversation before, sorry.  Cmd + click is also brining up the right-click menu for me, maybe we should try shift-click?

**Comment by Manindra29** [comment]
Why is Cmd+Click bringing up the right click menu?! Wasn't ctrl + click the default for right click? Is this behaviour specific to your system or a default Mac thing? I wasn't seeing this on my 10.8 VM.

**Comment by shiffman** [comment]
Oops, sorry, yes, maybe this is something weird with my system.  I'll check on a couple different machines and let you know.

**Comment by Manindra29** [comment]
Yeah, I'd have sorted this one out, but I can only test things to a certain extent with the OS X VM. Don't have a mac.. :(

**Comment by Manindra29** [comment]
Did you check back? Is it working now?

**Comment by shiffman** [comment]
I can't explain it, but only in processing on two different 10.8 machines, I am getting right-click for both cntrl and cmd (in Java mode as well).  The rest of the OS, cntrl-only. @benfry do you know if this is a Processing behavior?

**Comment by atduskgreg** [comment]
Both ctrl+click and cmd+click bring up the contextual popup menu for me on OSX 10.8+. And the menu gets stuck floating in space when the focus point changes.

![screen shot 2013-09-25 at 10 00 12 am](https://f.cloud.github.com/assets/165/1209501/ef893ed0-25ea-11e3-8711-698b6c39cea3.png)

**Comment by knupel** [comment]
OS 10.7.5
Ok, I understand now what you want !
Ok for me CMD + clic left = clic right

**Comment by Manindra29** [comment]
And what behaviour do you see when you Cmd + Left Click on any variable name in the regular Java mode? 
I need to find out if this is a Processing behaviour or PDE X behaviour. Afaik, on Mac, Ctrl + Left Click acts as Right click.

**Comment by knupel** [comment]
On Java mode and Mac 10.7.5

Ctrl + Click Left = Cmd + Click Left = Click Right but don't need to click on variable, same behaviour if I click on empty area of the sketch.

![capture decran 2013-09-26 a 23 34 08](https://f.cloud.github.com/assets/3332269/1221856/c1408402-26f3-11e3-931b-0ccd144dcef2.png)

**Comment by Manindra29** [comment]
This seems like in a bug in the JEditTextArea component, and not something on PDE X's side. I opened an issue in the main repo. Waiting for comments from @benfry.

**Comment by Manindra29** [comment]
Now fixed for the next Processing release. See https://github.com/processing/processing/issues/2103
