### ISSUE TITLE
error friendly-ifying

### ISSUE THREAD

**Issue by shiffman** [processing/processing-experimental#14]
We've discussed this before, but I'm opening an issue just to keep track of where we are regarding parsing and rewriting some error messages to make them friendlier than the default java.  @Manindra29 I recall there is a way to have PDE X store all your errors from a session in a text file.  Can you remind me how this works or perhaps add a TXT file to the repo with a list of common error messages?

**Comment by Manindra29** [comment]
You can enable logging of error messages from the option in the Debug menu. This is Editor specific and off by default.
Edit: And the log file is in csv format, so that it can be imported into spreadsheet software.
