### ISSUE TITLE
Void is not void

### ISSUE THREAD

**Issue by hex705** [processing/processing-experimental#18]
Maybe I did something wrong -- no one else is mentioning this so ??

I only get Void -- with a capital V -- not void with a small v.

Processing 2.0.3, OSX

steve

**Comment by Manindra29** [comment]
The 'Void' that you're seeing is a class belonging to java.lang package. 'void' is a java keyword. Presently, java keywords aren't suggested in the completion list. 

This is something that we're looking to improve.

**Comment by hex705** [comment]
ah --  thanks.  interesting tool -- will continue to explore.

s
