### ISSUE TITLE
completion pop-up gets stuck frequently

### ISSUE THREAD

**Issue by atduskgreg** [processing/processing-experimental#19]
Sometimes filled with completions, sometimes simply empty like this:

http://www.flickr.com/photos/unavoidablegrain/9901779905/

In this case it happened when I clicked away from the current cursor position in mid-completion, but I've seen it happen in other situations as well.

**Comment by Manindra29** [comment]
Can you find a way to reproduce the problem with a specific sketch? That'd be a great help in isolating the bug. 
[Edit] - Okay, I can reproduce it mostly by clicking on a line where the cursor isn't present currently, while the completion list is shown.

**Comment by knupel** [comment]
Same problem for me

Hello, I try today PDE X. Sound very good and I want use.
But I have problem with white window suggestion don't dissapear.
I try with few sketches the problem back again.
I must move my sketch to continue !
My computer is Imac 2,5 GHz Intel Core i5 / Version 10.7.5 / Processing 203
![capture decran 2013-09-24 a 21 39 34](https://f.cloud.github.com/assets/3332269/1203835/6edf9512-255a-11e3-8582-f2debc41bf2c.png)

**Comment by Manindra29** [comment]
Fixed for next revision.

**Comment by Manindra29** [comment]
@atduskgreg @StanLepunK I just posted a new version of PDE X. Please comment here to confirm when you see the update. I'm not sure how well the update system of the Contribution Manager is working.

**Comment by atduskgreg** [comment]
Just updated. Haven't tested it too thoroughly yet, but seems to be much improved. I couldn't trigger the bug easily.

**Comment by knupel** [comment]
Thanks for this very good tool, Work perfectly now.

**Comment by Manindra29** [comment]
This is unrelated, but since you guys are on mac, can you check how well the scroll to definiton feature works? Cmd + Left Click on a variable/method or class name should scroll to its definition, without triggering any popup menus.

I want to know if others are seeing #11 too.

**Comment by atduskgreg** [comment]
Just did. I'm definitely seeing that behavior too.

**Comment by knupel** [comment]
I don't understand exactly what you need, 
But on the dropdown menu, when i write var/methode i can with a double clic write quick the variable/class/method selected that I want.
And the mouse scroll left/right work perfectly.
But nothing happen when I'm on var/class/methode in the dropdown and I use CMD + Left Button of the mouse.
