### ISSUE TITLE
Status bar issue with live-error-checker.

### ISSUE THREAD

**Issue by aengelke** [processing/processing-experimental#2]
1. Create a new tab.
2. In the status bar appears a yellow background with text, a text field and buttons.
3. After about 1 second, the text with the yellow background hides.

Original issue: processing/processing#1837

**Comment by Manindra29** [comment]
It's kinda fixed now. If you try to create a new tab when caret is not on a line containing errors, it works. But when on an error line, the error message is displayed instead. Will tidy it up soon.
