### ISSUE TITLE
"void" should not get corrected to "Void"

### ISSUE THREAD

**Issue by atduskgreg** [processing/processing-experimental#20]
![screen shot 2013-09-24 at 6 25 18 pm](https://f.cloud.github.com/assets/165/1204585/3cf685c0-2568-11e3-8b53-a1bedb42b992.png)

For example when I'm trying to type:

```
void setup(){
}
```

This makes for a particularly bad user experience as it's the very first correction any user will see.

**Comment by Manindra29** [comment]
Duplicate of #18

**Comment by atduskgreg** [comment]
Ah, agreed. Missed that one. Sorry!
