### ISSUE TITLE
code completion window gets stuck when Processing loses focus

### ISSUE THREAD

**Issue by atduskgreg** [processing/processing-experimental#21]
![screen shot 2013-09-24 at 6 48 56 pm](https://f.cloud.github.com/assets/165/1204730/b6af1a82-256b-11e3-9a80-9ef222c3a102.png)

As one is often tabbing back and forth between Processing and documentation of some kind, this is particularly troubling.

**Comment by Manindra29** [comment]
Thanks for reporting. Will fix in the next release.
