### ISSUE TITLE
Problem with Library ProTablet

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#22]
Hello,
When I launch my sketch in Java Mode no problem, but when I launch with PDEX
I receive this message from console
invalid Class-Path header in manifest of jar file: /Users/stanislasmarcais/Documents/Processing/libraries/ProTablet/library/jpen-2.jar

Stan

**Comment by Manindra29** [comment]
Can you give me this library's download link? I can't seem to find it in the library manager.
Edit: Never-mind, found it.

**Comment by Manindra29** [comment]
If you look at the manifest.mf file inside jpen-2.jar(present in the library folder), the last line is `Class-Path:`
This is causing the error.

**Comment by knupel** [comment]
The Download link now is just Tablet from Andres Colubri, proTablet is the old style, but the same error happen with the new library Tablet.

What can I do for this error path ?
That's ok in JAVA, but not with PDEX

**Comment by Manindra29** [comment]
Until I'm able to fix the bug, you can try editing that file - just delete the last line in manifest.mf. It may work.

**Comment by knupel** [comment]
Thanks for the advice. I try to delete the last line like you write, but I cannot.
I use Java decompiler to see what's happen in the file.jar
![capture decran 2013-10-07 a 13 42 17](https://f.cloud.github.com/assets/3332269/1279973/a828524c-2f45-11e3-847e-21b9ddf0c62f.png)

**Comment by Manindra29** [comment]
Try this:
- Extract the jar file using a file compression utility.
- Edit the manifest.mf file.
- Package the contents back to a .zip file.
- Rename it back to the original jar file name including .jar extension.

It worked for me. I don't get the error anymore.

**Comment by knupel** [comment]
I don't understand what you mean ? I don't manage to extract the file jar. I try with stuffit but nothing happen. I try with the mac utility same result. I just manage to compress the file with stuffit, not extract. May be it's not possible on Mac ?

![capture decran 2013-10-07 a 15 06 58](https://f.cloud.github.com/assets/3332269/1280437/1cdc3f16-2f52-11e3-8591-39d73e4d871e.png)

**Comment by Manindra29** [comment]
Try this http://www.kekaosx.com/en/. Or some other 3rd party file compression utility. I use 7zip, for example.

**Comment by knupel** [comment]
Sure,my brain is to small but with Keka the only thing i Can make it's that : jpen-2.jar.7z but what can I do with that ? It's a compress thing, isn't it ? I have no menu to extract somethiong from a jar file.
Excpet JD-GUI but like i show you at the beginning...I delete the line in the Manifest.mf it's impossible. 

May be I must wait your next relase of PDEX ?

**Comment by Manindra29** [comment]
Beginners can find it a bit complex. No worries, here's a link to the edited file: https://www.dropbox.com/s/xmnd8drriazdph9/jpen-2.jar

**Comment by knupel** [comment]
Thx a lot @Manindra29  work perfectly now.

**Comment by knupel** [comment]
I open post about this problem on the Github tablet of Codeanticode, if you have a little time to explain to Andres the problem, that's great 
https://github.com/codeanticode/tablet/issues/1
thx
