### ISSUE TITLE
Code-Completion sometimes doesn't close.

### ISSUE THREAD

**Issue by aengelke** [processing/processing-experimental#23]
It leaves a gray, ugly window black, which makes some parts of the code unreadable.

EDIT: To reproduce on Windows 7:
- Type `size`
- Resize the PDE window
- Type `(5,` and then Enter
- (It stats `size(,)5,` in the editor, but anyway)

Sometimes it happens even without resize.
![image](https://f.cloud.github.com/assets/4236689/1274409/a0dbae1a-2d9e-11e3-905e-19cf649442d5.png)

**Comment by Manindra29** [comment]
This was a bug in v1.0.0b, was fixed in version 1.0.1b. See #19. Which version of PDE X are you using?
