### ISSUE TITLE
Styling detail: Code completion design on Windows

### ISSUE THREAD

**Issue by aengelke** [processing/processing-experimental#24]
I don't know whether it is possible/you want to implement that:
- The completion window has a 4 px gray border on Windows. Remove??
- The completion windows scrollbar is big on windows. Is it possible to use a scrollbar with a with of 5 pixels?

**Comment by Manindra29** [comment]
Which version of PDE X are using? Please try the latest one. The border width was decreased.

Modifying the scroll-bar width is mostly a cosmetic change, and doesn't seem to be worth the effort right now. I'm focusing on fixing core bugs and improving functionality. I'm open to pull requests though.
