### ISSUE TITLE
Slowdown

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#25]
just a comment about PDEX.

When I want create a void, a var some time I use this void before to be define this one, and after I write this one.
I remark if I do that with PDEX, Processing cursor slowdown and the result i write slower !

It's same when I use a var before to be define this one.

I don't know if my comment make sens ?

Maybe it's stupid to write a word, void, var before to have define this one...but it's my process to write sometime...maybe i'm not alone in this case, to write freely.

**Comment by Manindra29** [comment]
I'm afraid I can't understand the problem clearly from your description..

**Comment by knupel** [comment]
For example : 
I creat a var call "boolean clickLeft ; " and I use this one in a lot places in my sketch. But after I want change the name of this one for "boolean clickShortLeft ; " when I do that Processing Freeze for a long time and restart to show there is a probleme on the line with the var clickLeft is used, 
and the console say " clickLeft cannot be resolved to a var" , that's ok because this var don't exist now.
The problem is the freezing time. 

That's happen not all the time. I don't fing exactly when. Often when I try to use the var suggest in the dropdown menu, and this one give me a new bad var like on screen capture, because he create a var with the beginning of the word, but don't remose the last part, so he create a strange new word...
![capture decran 2013-10-09 a 11 53 57](https://f.cloud.github.com/assets/3332269/1296539/8ad69a34-30c9-11e3-9c69-996d5463a37d.png)

I hope it's clearer now ?

**Comment by Manindra29** [comment]
Ah, I see. The renaming feature isn't completely robust yet. This is an instance where renaming fails to work - clickShortLeftLeft is not expected. Can you please share with me the sketch so that I can debug it? 
Thanks for reporting this.

**Comment by knupel** [comment]
Ok, the sketch is really big, it's my project romanesco. So I give you juste one part of the project, you're the first to hear a piece of news romanesco before I drop this one in few weeks on Github,  :) https://www.dropbox.com/s/x29ex2s4ayz72r2/Scene_24b.zip if you want see the full project downloadable in the alpha 23 you can look on the web site http://romanescoproject.wordpress.com/ and if you'ave comment about my code is welcome :)

I think something to resolve that, it's when we have the dropdown menu to suggest a new word(var, void...) and we select one of them, PDEX take all the word in the sketch not just a previous part, so in my case the result it's dirrectly "clickShortLeft" and not "clickShortLeftLeft " because when I change the var with the dropdown menu the cursor text are in the midlle of the word....i don't now if it's clear, because it's hard to explain with the words and the english is not my mother language !

**Comment by Manindra29** [comment]
Closing this one. I'll create a new issue for the refactoring bug.
