### ISSUE TITLE
PermGen Space

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#26]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: PermGen space

Sometime I receive this message, when I want change some something in the code and the app is still open, or when I change var for the other, or maybe when  a lot sketches is open. I don't exactly when I receive this message. After that Processing slowdown, I cannot quit Processing normally, I must use the finder command to force Processing to quit.

**Comment by Manindra29** [comment]
This is a known issue(#1). After opening more than 6-7 sketches in one session, a restart of Processing is needed to avoid this error.
