### ISSUE TITLE
dropdown menu

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#28]
In the dropdown menu there is a little bug

he switch the color var for a int var.

for axample is I create 
void stuff(color c) {} the dropdown menu suggest void stuff( int c ) that's work but it's not optimum :)

**Comment by Manindra29** [comment]
Yeah, color variables are basically int types. It's a minor enhancement, but will require a lot more effort for a little gain.

**Comment by Manindra29** [comment]
Marking this as won't fix.
