### ISSUE TITLE
Statusbar update bug

### ISSUE THREAD

**Issue by aengelke** [processing/processing-experimental#29]
Type `new PApplet().line(100, 100, 100, 100);`. 
The statusbar will remain red, although there is no red color in the code at all.
(The code completion won't popup after the dot)

**Comment by Manindra29** [comment]
new `ClassName().` should trigger a completion popup. Will look into this bug.

The status bar gets updated if you move the cursor to a new line. This is a limitation imposed by the current editor status implementation. Will add it to the todo list for future.
