### ISSUE TITLE
CMD + L egronomic suggestion

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#31]
I try this command but there is "cosmetic problem" the pop-up is lock on the rigth of processing window so the result is very weird : 
I think is better to lock the popup on the left-side.
![capture decran 2013-10-22 a 09 50 27](https://f.cloud.github.com/assets/3332269/1385483/8e6d38ce-3b5f-11e3-9ae2-df2bb0217ebf.png)

**Comment by Manindra29** [comment]
That shouldn't be happening. I've not been able to reproduce this bug. Can you please provide exact steps to reproduce this bug?

**Comment by knupel** [comment]
Weird I think answer at this bug post on other issue, never mind.
That's happen when I use a shortcut or by dropdownmenu.
My mac is an iMac 2012, OS 10.7.5, same bug with P203 and P210.
the popup window suggest is lock on the the right side of the sketch window and take a big place, maybe the problem is from the size of this popup window. I've feeling the size of popup depend of the sketch size window ?

![capture decran 2013-12-04 a 09 57 25](https://f.cloud.github.com/assets/3332269/1671703/287d7d10-5cc2-11e3-9ce5-39aa20f34b5d.png)

**Comment by Manindra29** [comment]
The width of the sketch outline popup depends on the max length of the function name in the outline. What's the longest function name in your sketch? (Edit: Maybe I need to keep a cap on the max width of the list)
Also, it was decided to be placed on the right so that it doesn't obstruct the visibility of sketch code in the editor(as seen in the above screenshot). Edit: I'll give the placement some more thought.

**Comment by knupel** [comment]
Ok, I've a big big void, I understand now the problem. Maybe it's better to make a popup windows than can move ?
![capture decran 2013-12-04 a 12 15 04](https://f.cloud.github.com/assets/3332269/1672590/8d969fac-5cd5-11e3-8f37-3b1d473191f9.png)

**Comment by Manindra29** [comment]
I'll try setting a max limit on the sketch outline popup width and see how that works out. It should prevent the window from being weirdly wide.
@shiffman, do you have any suggestions on this issue? Should we try alternate positions for this window?

**Comment by shiffman** [comment]
Let's try a max width for now, I agree that seems like a good bet.  I don't have a good idea for a different placement at the moment.

**Comment by knupel** [comment]
Idea : keep the the right lock position. with a max width like 1/3 of the window sketch width size (with a minimum of course), and why not add an horizontal scroll for the longest function ?
