### ISSUE TITLE
Auto-Save

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#36]
Witht the  recurent freezing problem, and I lost all the work because I don't save so often. 
Why not add an autosave in processing, not directly in the sketch folder but like the other software in autosave folder. 
And when we re-open processing, processing ask if we want open all the auto-save sketches ?

**Comment by Manindra29** [comment]
This sounds like a good idea. Should be helpful during the beta period. I'll get started on this one soon. 

Okay, currently thinking of implementing an auto save timer that saves a copy of the sketch every 5 minutes to a temporary folder inside the sketch folder. When the user closes the sketch normally, this temp folder will be deleted. In case of a crash, this folder will persist. So when opening the sketch again, if temp folder exists, user will be prompted to restore the sketch if he wants.

**Comment by Manindra29** [comment]
Now implemented in v1.0.3b. Please try it out and let me know how it goes.
https://github.com/processing/processing-experimental/releases/tag/1.0.3b

**Comment by knupel** [comment]
There's no more autosave now with PDEX in Processing 3 ?
