### ISSUE TITLE
extract method

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#40]
Just an idea to copy a part of code to create a methode : 
When you copy a part of code with the right click contextual menu, may be it's possible to add a line like "copy to create void"
and after when we past this one by contextual menu, we've a line "past void"
and automaticly Processing write
void title() {
text copy ;
}

make sens ?

**Comment by Manindra29** [comment]
I have a similar feature in mind planned ahead. Stay tuned. 
Closing this for now.
