### ISSUE TITLE
Crash 1.0.3b

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#41]
I test this version immediatly, but no time to test, Processing crash before the opening see the screen shot. OS 10.7.5 iMac 2012
![capture decran 2014-01-21 a 13 10 33](https://f.cloud.github.com/assets/3332269/1963139/9f364bb4-8295-11e3-991e-6686bff47e6e.png)

**Comment by Manindra29** [comment]
Damn, that one was a major blooper! Edited a value in the last moment and messed up. :(
Fixed: https://github.com/processing/processing-experimental/releases/download/1.0.3b/ExperimentalMode_v1.0.3b.zip
Thanks for your patience.

**Comment by knupel** [comment]
IT's better, now Processing can opening !! I test ASAP !

**Comment by Manindra29** [comment]
Phew. A temporary _autosave folder is created in the sketch folder, which stores a backup of the sketch folder every 3 minutes(duration can be configured in preferences.txt). This _autosave folder is deleted if Processing exits normally. In case of a crash, PDE X can find this folder in the sketch folder and load the last saved backup if user wants to.
