### ISSUE TITLE
Tweak Mode

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#42]
I just try the tweak mode and I think it's very experimental and nice mode to work may be it's possible to add this mode in PDEX  ?
@galsasson 
@Manindra29

**Comment by Manindra29** [comment]
I'm afraid there are no such plans as of now. The present goal is to make PDE X fully stable.

**Comment by knupel** [comment]
for sure you can close this issue dream :)

**Comment by Manindra29** [comment]
Shall keep you posted if there's any development in this regard.

**Comment by fjenett** [comment]
Reopened as suggestion for GSOC14

**Comment by Manindra29** [comment]
Now integrated, thanks to the awesome @galsasson!

**Comment by knupel** [comment]
congratulation for this work !
