### ISSUE TITLE
Freeze 

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#43]
Processing freeze very often when this error come
" var cannot be resolved to a variable"
and restart sometime after few seconds, when the autosave is done.

last PDEX on Processing 211 with OSX 10.7.5

**Comment by Manindra29** [comment]
" var cannot be resolved to a variable" - how often do you see this error message? Can you share some sample code?

It's unlikely that this particular error message could be causing the freeze up.

**Comment by knupel** [comment]
ok I try to write a simple code because this problem is on my Romanesco Project, and it's little big code.

**Comment by Manindra29** [comment]
Also, do you see any error message in the console during the freeze up? (You can turn on Show Debug Messages in PDE X settings)

**Comment by knupel** [comment]
Now I'm on maverick 10.9.2 with Processing 212. It's very stable, no crash, no freeze at this time.
