### ISSUE TITLE
Auto-Save problem

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#44]
When we save in manual mode after the autosave, this sentence error come. So it's not possible to save, except if we save to an other version ?
I'm not sure to be clear.

![capture decran 2014-01-30 a 18 27 53](https://f.cloud.github.com/assets/3332269/2042632/e8a6798c-89d3-11e3-9f51-e46017425cf5.png)

**Comment by Manindra29** [comment]
When you recover a sketch via auto save, you got to select the 'Save As' option. Currently the auto save back up is saved in a temporary folder, therefore you can't save the recovered sketch into that folder.

**Comment by knupel** [comment]
After one week of using : 
The autosave have very weird behavior.
Sometime there is autosave, sometime no, but  often there is no autosave, and freeze after "name var cannot be resolved to a variable" in 90% of time the freezing is without comeback. I think the problem "name var cannot be resolved to a variable" come with the huge sketch.

And if the autosave is active the classic save don't work : Processing Display "No such file or directory" we must save  in other directory, So I use "save as" like you suggestion, but I think is not really good option. For example if I work with a sketch connected on Github, at the end I must change the name of the folder and the main tab to Github, and Github don't regonize the + and - line of the code and he just change all the repository for the new one.
I think we must can save with just "save" on the file we've open, and don't use the way "save as".

To finish.
Suggestion : in the dropdown menu I think a line to change the time of save and switch on/off the autosave can be welcome... just for information I don't find where is the file preference ;)

Sorry for the bad word, the auto-save is good but I think the way to be stable is far. But when the autosave work, I test it too, it's very nice.

**Comment by Manindra29** [comment]
Fixed. See #62

**Comment by knupel** [comment]
Yes !

**Comment by Manindra29** [comment]
I've only disabled the feature. It'd great if you can test 1.0.4b to see if this problem still persists. 

Development effort was focused on other bug fixes in the last few months. Auto-save isn't an easy feature to get 100% right. It's still on my todo list, will take a shot at it again soon. 

Apologies again for any data loss you may have suffered. Thanks for bearing with us.

**Comment by knupel** [comment]
hmmm. No problem for the lost time, if a the end the PDEX is better.
So I remove the previous version of PDEX, and after Processing don't ask to re-install the new one, but just "undo". So I don't know if I have the new one or not? Where I can see if I have a good version of PDEX ?

**Comment by Manindra29** [comment]
@StanLepunK  You can check the version in <sketch-book>/modes/ExperimentalMode/mode.properties file. It's the `prettyVersion` field.

**Comment by knupel** [comment]
Ok that's 1.0.3 b. I try to remove from this folder to see I can reload the good one.

**Comment by knupel** [comment]
I failed to install PDEX104.
When I remove the PDEX103 from the folder, then I download, the downloading version is PDEX103.
So i'm smart and I download from Github PDEX104 and change the name of the folder for "ExperimentalMode" but P212 see nothing.
Sorry for my "incompétence" which way to install the last release of PDEX ?

**Comment by Manindra29** [comment]
Manual Steps to remove a mode: 
- Close Processing
- Open `<your sketchbook>\modes` folder.
- Delete the folder of the mode you want to remove. For PDE X, I would delete the ExperimentalMode folder.

Manual Steps to install a mode:
- Download the zip file of the mode. Latest version of PDE X is always [here](http://download.processing.org/pdeX.zip). All versions can be found [here](https://github.com/processing/processing-experimental/releases)
- Copy the zip file into `<your sketchbook>\modes` folder
- Extract the zip file 'as is' in the modes folder (basically extract zip contents into the modes folder without any modifications). For PDE X, you should see a `<your sketchbook>\modes\ExperimentalMode` folder.
- Restart Processing

**Comment by knupel** [comment]
Perfect with the good file and the good information, that's better.
I give my feed back ASAP
