### ISSUE TITLE
Export App don't work

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#45]
Hello,
I try to export app from Processing 211 on mac 10.7.5 with Java 7.51 with PDEX open
but when I try to launch I receive this message, when PDEX is not active the export app work.
![capture decran 2014-02-05 a 12 12 38](https://f.cloud.github.com/assets/3332269/2086395/744c0188-8e56-11e3-9a71-2dbd4ecd621e.png)
don't work too with Processing 210, but work with Processing 203

**Comment by Manindra29** [comment]
This must be an issue with the export application files, they must have been updated in the PDE. I shall update them in the next release.

**Comment by Manindra29** [comment]
For a more permanent fix, changes are required in JavaMode. See https://github.com/processing/processing/issues/2399
