### ISSUE TITLE
Open from Auto-Save

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#48]
Hello,
Sometime when the autosave work and Processing crash, I use the autosaved and it's good, but I cannot open directly from the folder, I must open Processing before and open my sketch after. it's a little thing.
The second is when I used the autosaved I cannot saved on the the main sketch, after I must use the autosaved folder all the time...big problem !
![capture decran 2014-03-06 a 13 15 20](https://f.cloud.github.com/assets/3332269/2344809/821481c0-a529-11e3-88a4-c7917c1b1ff8.png)

**Comment by Manindra29** [comment]
The second issue is definitely serious. I'm already working on improving the auto save feature. I'll also add an option to turn it off, just as a safety measure.

As a stopgap measure what you can do presently is - When you recover a saved sketch, use the 'save as' option to save it as a new sketch.

**Comment by knupel** [comment]
very good news to read you work on it.
I try to use PDE because it's very nice for the big code, but that's crash so often. Just now in one hour...maybe 10-12 freeze-crash !
And look the image of the autosave folder
![capture decran 2014-03-06 a 15 11 26](https://f.cloud.github.com/assets/3332269/2345738/8f4e7976-a539-11e3-86e6-07e5e4b84fc7.png)

**Comment by Manindra29** [comment]
I'm aware of this folder bug and it's been fixed in the source. Please wait for the next release. In the meantime you can use the default Processing mode for working on critical sketches.

**Comment by knupel** [comment]
it's balance...because I need many option from PDEX to see where is the old var to change for the new var ! :)
