### ISSUE TITLE
PApplet methods code completion suggestions

### ISSUE THREAD

**Issue by shiffman** [processing/processing-experimental#6]
I wonder if we should include only the methods from PApplet or everything under the sun in JAVA.  It seems a little much to have everything, i.e.  

![screen shot 2013-07-17 at 9 32 04 pm](https://f.cloud.github.com/assets/191758/816534/e0ece052-ef49-11e2-9bf0-f2038e1bbcb7.png)

**Comment by Manindra29** [comment]
I think that classes from certain packages like org.eclipse or sun.security, etc are almost certainly not going to be used. Right now, all classes that ship with the jre get picked up. Maybe I'll make a list of packages that won't be part of the completion list unless explicitly imported? 

Besides, if you may have noticed, the items in the list follow a sorting order: local > predefined code and fields > methods > classes. Methods have higher precedence over classes. So PApplet methods appear on top of the list.

**Comment by Manindra29** [comment]
Only "java.*" packages form a part of the list now. Other classes need to be explicitly imported before they're shown in completion list.

**Comment by shiffman** [comment]
great solution! look forward to trying it out.
