### ISSUE TITLE
PDE X fails to load with Processing 220

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#64]
When we switch from Java mode to PDEX mode the sketch close.
This problem don't come with the Tweaks Mode.

OS Maverick / Processing 220 / PDEX 104 (pretty version) / Imac 2012

**Comment by aengelke** [comment]
This occours on Windows and Linux, too. It might be sufficient to just recompile PDE X, because the signature of the Toolkit.setIcon changed.

**Comment by Manindra29** [comment]
There was a recent change in the 2.2 release which is causing this issue. Thank you @aengelke for identifying the cause. I'm a bit busy these days with my final exams, will release an update as soon as I can.

**Comment by benfry** [comment]
Was worried this might be an issue (as can be seen in the commit). I'll make the change and post a 2.2.1.

**Comment by aengelke** [comment]
Just rebuilt PDE X from source, and everything works fine, so 2.2.1 may be unnecessary.

**Comment by Manindra29** [comment]
@aengelke But this function is also used by contributed tools to set the icon for their dialogs/windows. Won't they probably break(like PDE X) if the older method is removed?

**Comment by aengelke** [comment]
They just have to recompile, that Java can update the method signature.

**Comment by benfry** [comment]
The method signature change requires a recompile, which will break backwards compatibility for those modes. Didn't realize how prevalent use of that function was (see notes in the source). It's coming back with the old signature in 2.2.1.

**Comment by aengelke** [comment]
With 2.2.1, this issue can be closed.
