### ISSUE TITLE
UI issue: "Show Usage..." issues "Can't locate definition whatever" that flashes to fast

### ISSUE THREAD

**Issue by jas0501** [processing/processing-experimental#65]
Trying to get a "Show Usage..." display on something that can't be located issues a message that just flashes and is difficult to see.

Maybe place the message in the "Usage of" window instead.

**Comment by Manindra29** [comment]
Can you please post a sketch with which the bug can be reproduced? Do post steps to reproduce the error.

**Comment by jas0501** [comment]
Do usage on stroke
//=========================
void setup()
{
 size(300,300); 
 stroke(12);
}

void draw()
{
  text("Text",20,20);
}
//==========================

**Comment by Manindra29** [comment]
For now, Show Usage only works for methods, variables and classes which have been defined in the Sketch itself.

There are no immediate plans for extending the support for all methods, vars and classes.

**Comment by shiffman** [comment]
Just discovered this myself!  I think we need to have a more graceful error when the user tries to do show usage or rename on a variable/method they did not create (or other weird things like a number, etc).

**Comment by Manindra29** [comment]
Ah, I think you're right. Even while refactoring, this will be a possible issue for non user defined variables.

I'll first try to see if the options for refactoring and show usage can be grayed out for stuff it can't handle. Otherwise, a more graceful error message. Sounds good?

**Comment by Manindra29** [comment]
Alright, I've made changes to how the status message is displayed. Now the error message gets displayed for 2 seconds before disappearing.

**Comment by Manindra29** [comment]
When user tries to rename pre-defined classes, methods, etc, the rename dialog is no longer displayed. (See #69)

**Comment by Manindra29** [comment]
Fixed for next release.
