### ISSUE TITLE
Separate Debug Menu for Debugger items

### ISSUE THREAD

**Issue by Manindra29** [processing/processing-experimental#71]
At present, PDE X menu has 22 items. Out of these 15 items are related to the Debugger. 

![pdexmenu](https://cloud.githubusercontent.com/assets/1686425/3373750/bc5430b8-fbb6-11e3-97b9-b1402d0a7d98.png)

The idea is to have a separate Debug Menu for these items. It shall remain hidden on first start up.

Q: How should the user enable/toggle the Debug Menu?
@shiffman @REAS

**Comment by benfry** [comment]
Error Checker Enabled, Warnings Enabled, Code Completion Enabled should all be in the Preferences window.

Show Debug Messages, Write Errors to Log, and perhaps Show Outline should live only in preferences.txt (Show Outline I'm not familiar with)

PDE X on Github can be removed; not a bad idea for us to add a Github link in the Help menu if we don't have one already.

The rest should just be the Debug menu, and then we'll sort out their naming and placement over the summer.

**Comment by Manindra29** [comment]
Alright, I'll update the Preferences window with these settings.

> (Show Outline I'm not familiar with)

It brings up the [quick navigation pane](https://github.com/processing/processing-experimental/wiki/Getting-Started#quick-navigation).

> PDE X on Github can be removed; not a bad idea for us to add a Github link in the Help menu if we don't have one already.

We don't have it right now. I think we should add a GitHub link.

> The rest should just be the Debug menu, and then we'll sort out their naming and placement over the summer.

Cool. I'll just rename the current PDE X menu to Debug and leave the Debug menu items untouched. Will move the PDE X toggles into Preferences.

**Comment by Manindra29** [comment]
Implemented with https://github.com/processing/processing/commit/cda60dd021050c1d6c08785b4428b9eb30bceae4
