### ISSUE TITLE
Move PDE X menu items into one of the default menus

### ISSUE THREAD

**Issue by Manindra29** [processing/processing-experimental#72]
Now that PDE X is the default mode, into which of the default menu should the items be moved?

The items would be mostly toggles for enabling/disabling features like code-completion/error-checking/warnings etc. Total of 7 items. See #71 
@shiffman @REAS

**Comment by benfry** [comment]
I've added notes to #71...

**Comment by knupel** [comment]
Congratulation for that @Manindra29
