### ISSUE TITLE
Var not used

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#74]
Sometime PDEX indicate a local var is not used, but this one is used in the loop just behind like "whichOne" in the screenshot
![capture decran 2014-06-27 a 11 27 46](https://cloud.githubusercontent.com/assets/3332269/3409798/9a32ca3e-fddd-11e3-826e-6d32b0571021.png)

**Comment by Manindra29** [comment]
Can you share the code of the complete method?

**Comment by knupel** [comment]
whaou it's huge, it's from my project. I try to reproduce this week-end in smaller sketch.

**Comment by Manindra29** [comment]
Not the whole sketch, but can you share the code of the lookAndDisplayInfo() method? I think you're just assigning some value to the variable but not putting it to any real use.

**Comment by knupel** [comment]
ok voilà : 
I understood you are right I don't use this one after.
May be it's possible to mark the second one too ?

```
void setup() {
}

void truc() {
  int h ;
  for(int i = 0 ; i < 3 ; i++) {
    int id = 1 ;
    h = id ;
  }
}
```
