### ISSUE TITLE
File change detection

### ISSUE THREAD

**Issue by foriequal0** [processing/processing-experimental#75]
http://docs.oracle.com/javase/tutorial/essential/io/notification.html

I do often jump over git commits to do some experiments on my code. But every time I checkout commits, I have to shutdown and re-open pde.

It would be great if pde x can recognize changes of its opened files and automatically refresh them or notify user about the changes.

or at least, I think there must be exist a manual refresh button.

**Comment by Manindra29** [comment]
Thanks for the suggestion. I wasn't aware of this api. We'll consider it.
