### ISSUE TITLE
Command+H runs sketch

### ISSUE THREAD

**Issue by jeffThompson** [processing/processing-experimental#78]
On Mac, using the Hide shortcut `Command+H` runs the sketch! Using `Processing > Hide Processing...` works as expected.

**Comment by Manindra29** [comment]
Thanks for reporting the bug. Please note:
This repo is no longer active. PDE X codebase was merged into the main processing repo starting with the 3.0 alpha releases (July 2014), further development continues in the main repo. So please report any issues in the main Processing repo.
