### ISSUE TITLE
Windows 8 problem export 

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#79]
Hello, same problem like this issue https://github.com/processing/processing/issues/2806 
When I want export the app I receive this error
"launch4j-build.xml:4: taskdef class net.sf.launch4j.ant.Launch4jTask cannot be found  using the classloader AntClassLoader[]"
I try with P304 on windows 8.

**Comment by Manindra29** [comment]
Just tested this on Win 8 from the latest master. Export was working fine. I guess it got fixed after 3.0a4 release. So closing this.

Also, please note: This repo is no longer active. PDE X codebase was merged into the main processing repo starting with the 3.0 alpha releases (July 2014), further development continues in the main repo. So please report any issues in the main Processing repo.

**Comment by knupel** [comment]
Thanks... So now PDEX will be not experimantal is official ! Congratulation.
