### ISSUE TITLE
findall vs. rename

### ISSUE THREAD

**Issue by shiffman** [processing/processing-experimental#8]
When renaming a variable it's unclear to me what the buttons do.  What is "findall" relative to "rename"?

**Comment by Manindra29** [comment]
I might need to come up with a better name for the button. Its purpose is to show an overview of where all in the code the variable is referenced and thus would be changed after renaming. Do you think it might not be really needed? Eclipse has a similar preview feature while refactoring, so I imagined advanced users may wish to have the same. Also could add a hover tooltip to explain its use?

**Comment by shiffman** [comment]
maybe something like "show all" and "replace all"?  I'm not sure it's needed but maybe I need to play with it more.  I think it's ok to leave in for now.

**Comment by Manindra29** [comment]
How about 'Rename' and 'Show occurrences' ? Renaming isn't a simple find and replace operation after all, there could be local and global variables with same name. But then folks may find 'Replace all' more familiar..

**Comment by shiffman** [comment]
let's give that a try and see how it feels!

**Comment by Manindra29** [comment]
"Show Usage" - I think this is the one we were looking for. >:-)

**Comment by Manindra29** [comment]
In fact, I was wondering, why not make it a standalone feature as well? To show the usage of a class/method or variable throughout the sketch? I could add the option to the right click pop up menu.

**Comment by shiffman** [comment]
great, yes, I like this plan.

**Comment by clankill3r** [comment]
I think it would also be nice that if you select something it outlines words that are the same.
Just like in sublime. It's a bit like "Show Usage" without using the right mouse menu.

**Comment by Manindra29** [comment]
@cankill3r, It's a nice feature in Sublime, but I'm not sure if I would want the same in the PDE. I think it would add clutter.
